INSERT INTO category (description) VALUES ('Indian');
INSERT INTO category (description) VALUES ('Polish');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Each');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Clove');
INSERT INTO unit_of_measure (description) VALUES ('Small');
INSERT INTO unit_of_measure (description) VALUES ('Medium');
INSERT INTO unit_of_measure (description) VALUES ('Large');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
